import { defineStore } from "pinia";

export const useProductsStore = defineStore("products", {
  state: () => {
    return {
      products: [
        {
          id: "1",
          titel: "You are Loved T-shirt",
          omschrijving: "Met dit leuke t-shirtje straal jij deze zomer",
          afbeelding: "/t-shirt1.webp",
          prijs: 19.99,
          btw: 0.21,
          stock: 10,
          categorie: "kleding",
        },
        {
          id: "2",
          titel: "Kleurrijke wenskaartjes",
          omschrijving: "Wie maak jij blij met deze leuke wenskaartjes",
          afbeelding: "/kaartjes1.webp",
          prijs: 9.99,
          btw: 0.21,
          stock: 0,
          categorie: "kaartjes",
        },
        {
          id: "3",
          titel: "Soesjieee T-shirt",
          omschrijving: "Zei iemand Sooooeeeeesjieeee?",
          afbeelding: "/soesjieee1.webp",
          prijs: 15.99,
          btw: 0.21,
          stock: 3,
          categorie: "kleding",
        },
        {
          id: "4",
          titel: "Regenboog parel oorbellen",
          omschrijving: "Met deze oorbellen straal jij deze zomer",
          afbeelding: "/oorbellen.webp",
          prijs: 9.99,
          btw: 0.21,
          stock: 19,
          categorie: "kleding",
        },
        {
          id: "5",
          titel: "Parel oorbellen",
          omschrijving: "Met deze oorbellen straal jij deze zomer",
          afbeelding: "/parel_oorbellen.webp",
          prijs: 9.99,
          btw: 0.21,
          stock: 1,
          categorie: "kleding",
        },
        {
          id: "6",
          titel: "Bedankt Kaartje",
          omschrijving: "Wie maak jij blij met deze leuke wenskaartjes",
          afbeelding: "/bedankkaartje.webp",
          prijs: 9.99,
          btw: 0.21,
          stock: 15,
          categorie: "kaartjes",
        },
        {
          id: "7",
          titel: "Verjaardagskaartje",
          omschrijving: "Wie maak jij blij met deze leuke wenskaartjes",
          afbeelding: "/verjaardagskaartje.webp",
          prijs: 9.99,
          btw: 0.21,
          stock: 7,
          categorie: "kaartjes",
        },
        {
          id: "8",
          titel: "Beterschapskaartje",
          omschrijving: "Wie maak jij blij met deze leuke wenskaartjes",
          afbeelding: "/beterschapskaartje.webp",
          prijs: 9.99,
          btw: 0.21,
          stock: 5,
          categorie: "kaartjes",
        },
        {
          id: "9",
          titel: "Good Vibes T-shirt",
          omschrijving: "Only Good Vibes met dit leuke t-shirtje",
          afbeelding: "/goodvibest-shirt.webp",
          prijs: 15.99,
          btw: 0.21,
          stock: 4,
          categorie: "kleding",
        },
        {
          id: "10",
          titel: "Programmers T-shirt",
          omschrijving: "Met dit leuke t-shirtje straal jij deze zomer",
          afbeelding: "/programmerst-shirt.webp",
          prijs: 19.99,
          btw: 0.21,
          stock: 2,
          categorie: "kleding",
        },
      ],
    };
  },
});
